# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fillVector <- function(x, rev = FALSE) {
    .Call('tidyr_fillVector', PACKAGE = 'tidyr', x, rev)
}

simplifyPieces <- function(pieces, p, fillLeft = TRUE) {
    .Call('tidyr_simplifyPieces', PACKAGE = 'tidyr', pieces, p, fillLeft)
}

